import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { SignInButton, useUser } from "@clerk/nextjs";

import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";
import { LoadingSpinner } from "~/components/Loading";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;
  return <div className='flex gap-4 w-full'>
    <Image
      src={user.profileImageUrl}
      alt="Profile Image"
      className="w-16 h-16 rounded-full"
      width={64}
      height={64}
    />
    <input placeholder="Type only emojis ;)" className="bg-transparent grow outline-none" />
  </div>
}


type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div className='p-4 border-b gap-3 flex' key={post.id}>
      <Image
        src={author.profileImage}
        alt="Profile Image"
        className="w-16 h-16 rounded-full"
        width={64}
        height={64}
      />
      <div className="flex flex-col">
        <div className="flex gap-1 text-slate-300">
          <span>{`@${author.username}`}</span>
          <span className="font-thin">{`- ${dayjs(post.createdAt).fromNow()} `}</span>
          </div>
        <span className="text-2xl">{post.content}</span>
      </div>
    </div>
  )
}

const Feed = () => {
  const { data, isLoading: postsLoading } = api.posts.getAll.useQuery();

  if (postsLoading) return <LoadingSpinner />;

  if (!data) return <div>Something went wrong!</div>

  return <div className="flex flex-col">
  {
    data.map((dataPost) =>
      (<PostView key={dataPost.post.id} {...dataPost} />)
    )
  }
</div>
}

const Home: NextPage = () => {


  const { isLoaded: userLoaded, isSignedIn} = useUser();

  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full md:max-w-2xl border-x">
          <div className="border-b flex justify-center p-4">{
            !isSignedIn
              ? <SignInButton />
              : <CreatePostWizard />
          }</div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
